const cities = [
    { name: "Achakkar", price: 45, time: "24h - 48h" },
    { name: "Adjir (al Hoceima)", price: 45, time: "48h - 96h" },
    { name: "Afra", price: 39, time: "24h - 72h" },
    { name: "Afourar", price: 39, time: "48h - 96h" },
    { name: "Afsou (Nador)", price: 45, time: "24h - 72h" },
    { name: "Agadir", price: 35, time: "24h - 48h" },
    { name: "Agdz (Zagoura)", price: 45, time: "24h - 72h" },
    { name: "Agouidir", price: 45, time: "48h - 96h" },
    { name: "Agouim", price: 45, time: "24h - 72h" },
    { name: "Agourai", price: 45, time: "48h - 96h" },
    { name: "Aguelmous", price: 39, time: "48h - 96h" },
    { name: "Ahfir", price: 45, time: "48h - 96h" },
    { name: "Ahejarr Ennehal", price: 45, time: "48h - 96h" },
    { name: "Ain Aicha", price: 45, time: "48h - 96h" },
    { name: "Ain Attig", price: 35, time: "24h - 48h" },
    { name: "Ain chkaf", price: 39, time: "24h - 72h" },
    { name: "Ain Cheggag", price: 45, time: "24h - 72h" },
    { name: "Ain El Aouda", price: 35, time: "24h - 48h" },
    { name: "Ain Harrouda", price: 35, time: "24h - 48h" },
    { name: "Ain Lahcen", price: 45, time: "24h - 72h" },
    { name: "Ain Leuh", price: 45, time: "48h - 96h" },
    { name: "Ain Mediouna", price: 45, time: "48h - 96h" },
    { name: "Ain Taoujdate", price: 45, time: "24h - 72h" },
    { name: "Aïn Erreggada", price: 45, time: "48h - 96h" },
    { name: "Aïn-Béni-Mathar", price: 45, time: "48h - 96h" },
    { name: "Aït Amira", price: 39, time: "24h - 72h" },
    { name: "Aït Ben Haddou", price: 45, time: "24h - 72h" },
    { name: "Aït Boudaoud", price: 45, time: "48h - 96h" },
    { name: "Ait Daoud", price: 45, time: "24h - 72h" },
    { name: "Ait hadi", price: 45, time: "48h - 96h" },
    { name: "Aït Ishaq", price: 39, time: "48h - 96h" },
    { name: "Aït Kamara", price: 45, time: "48h - 96h" },
    { name: "Aït Melloul", price: 35, time: "24h - 48h" },
    { name: "Aït Ourir", price: 45, time: "48h - 96h" },
    { name: "Aït Sedrate Sahl Gharbia", price: 45, time: "48h - 96h" },
    { name: "Aït Tarzout", price: 45, time: "48h - 96h" },
    { name: "Ajdir (al Hoceima)", price: 45, time: "48h - 96h" },
    { name: "Bab Berred", price: 45, time: "48h - 96h" },
    { name: "Bab Taza", price: 45, time: "48h - 96h" },
    { name: "Bab Zitoun", price: 45, time: "48h - 96h" },
    { name: "Bachkou", price: 45, time: "48h - 96h" },
    { name: "Badiour", price: 45, time: "48h - 96h" },
    { name: "Bahla", price: 45, time: "48h - 96h" },
    { name: "Beni Ansar", price: 35, time: "24h - 48h" },
    { name: "Beni Ayat", price: 39, time: "48h - 96h" },
    { name: "Beni Boufrah", price: 45, time: "48h - 96h" },
    { name: "Beni Chiker", price: 45, time: "48h - 96h" },
    { name: "Beni Chougrane", price: 45, time: "48h - 96h" },
    { name: "Beni Drar", price: 45, time: "48h - 96h" },
    { name: "Beni Hassane", price: 45, time: "48h - 96h" },
    { name: "Beni Mellal", price: 35, time: "24h - 48h" },
    { name: "Beni Snassen", price: 45, time: "48h - 96h" },
    { name: "Benslimane", price: 35, time: "24h - 48h" },
    { name: "Berkane", price: 35, time: "24h - 48h" },
    { name: "Berrechid", price: 35, time: "24h - 48h" },
    { name: "Bouskoura", price: 35, time: "24h - 48h" },
    { name: "Bouznika", price: 35, time: "24h - 48h" },
    { name: "Cabo Negro", price: 39, time: "24h - 72h" },
    { name: "Casablanca - 2 mars", price: 35, time: "24h" },
    { name: "Casablanca - Abdelmoumen", price: 35, time: "24h" },
    { name: "Casablanca - Ain Borja", price: 35, time: "24h" },
    { name: "Casablanca - Ain Sebaa", price: 35, time: "24h" },
    { name: "Casablanca - Anassi", price: 35, time: "24h" },
    { name: "Casablanca - Ancienne Medina", price: 35, time: "24h" },
    { name: "Casablanca - Attacharok", price: 35, time: "24h" },
    { name: "Casablanca - Autres quartiers", price: 35, time: "24h - 48h" },
    { name: "Casablanca - Azhar", price: 35, time: "24h" },
    { name: "Casablanca - Bachkou", price: 35, time: "24h" },
    { name: "Casablanca - Beauséjour", price: 35, time: "24h" },
    { name: "Casablanca - Belvédère", price: 35, time: "24h" },
    { name: "Casablanca - Ben Msik", price: 35, time: "24h" },
    { name: "Casablanca - Bernoussi", price: 35, time: "24h" },
    { name: "Casablanca - Bournazel", price: 35, time: "24h" },
    { name: "Casablanca - Californie", price: 35, time: "24h" },
    { name: "Casablanca - Centre Ville", price: 35, time: "24h" },
    { name: "Casablanca - CIL", price: 35, time: "24h" },
    { name: "Casablanca - Derb Alkabir", price: 35, time: "24h" },
    { name: "Casablanca - Derb Ghalef", price: 35, time: "24h" },
    { name: "Casablanca - Derb Milan", price: 35, time: "24h" },
    { name: "Casablanca - Derb Omar", price: 35, time: "24h" },
    { name: "Casablanca - Derb Sultan", price: 35, time: "24h" },
    { name: "Casablanca - El Hana", price: 35, time: "24h" },
    { name: "Casablanca - El Hank", price: 35, time: "24h" },
    { name: "Casablanca - Floride", price: 35, time: "24h" },
    { name: "Casablanca - France Ville II", price: 35, time: "24h" },
    { name: "Casablanca - Garage Allal", price: 35, time: "24h" },
    { name: "Casablanca - Gauthier", price: 35, time: "24h" },
    { name: "Casablanca - Habous", price: 35, time: "24h" },
    { name: "Casablanca - Hay Al Inara", price: 35, time: "24h" },
    { name: "Casablanca - Hay Assalama", price: 35, time: "24h" },
    { name: "Casablanca - Hay el Farah", price: 35, time: "24h" },
    { name: "Casablanca - Hay Hassani", price: 35, time: "24h" },
    { name: "Casablanca - Hay Mohammedi", price: 35, time: "24h" },
    { name: "Casablanca - Hay Moulay Abdellah", price: 35, time: "24h" },
    { name: "Casablanca - Hay Moulay Rachid", price: 35, time: "24h" },
    { name: "Casablanca - Hay Tissir", price: 35, time: "24h" },
    { name: "Casablanca - Jawhara", price: 35, time: "24h" },
    { name: "Casablanca - La Gironde", price: 35, time: "24h" },
    { name: "Casablanca - Lamkansa", price: 35, time: "24h" },
    { name: "Casablanca - Les Hôpitaux", price: 35, time: "24h" },
    { name: "Casablanca - Lissassfa", price: 35, time: "24h" },
    { name: "Casablanca - Mandarona", price: 35, time: "24h" },
    { name: "Casablanca - Mers Sultan", price: 35, time: "24h" },
    { name: "Casablanca - Oasis", price: 35, time: "24h" },
    { name: "Casablanca - Oulfa", price: 35, time: "24h" },
    { name: "Casablanca - Palmier", price: 35, time: "24h" },
    { name: "Casablanca - Polo", price: 35, time: "24h" },
    { name: "Casablanca - Racine", price: 35, time: "24h" },
    { name: "Casablanca - Riveira", price: 35, time: "24h" },
    { name: "Casablanca - Salmia", price: 35, time: "24h" },
    { name: "Casablanca - Sbata", price: 35, time: "24h" },
    { name: "Casablanca - Sidi Belyout", price: 35, time: "24h" },
    { name: "Casablanca - Sidi Moumen", price: 35, time: "24h" },
    { name: "Casablanca - Sidi Othmane", price: 35, time: "24h" },
    { name: "Casablanca - Tantonville", price: 35, time: "24h" },
    { name: "Dar Bouazza", price: 39, time: "24h - 72h" },
    { name: "Dar Chabab", price: 35, time: "24h" },
    { name: "Dar El Beida", price: 39, time: "24h - 72h" },
    { name: "Dar Tounsi", price: 35, time: "24h" },
    { name: "Dcheira El Jihadia", price: 39, time: "24h - 72h" },
    { name: "Demnate", price: 39, time: "24h - 72h" },
    { name: "Deroua", price: 35, time: "24h" },
    { name: "Echemmaia", price: 39, time: "24h - 72h" },
    { name: "El Aarjate", price: 45, time: "24h - 72h" },
    { name: "El Borouj \"Région de Settat\"", price: 45, time: "24h - 48h" },
    { name: "El Gara", price: 39, time: "24h - 48h" },
    { name: "El Haouzia (el jadida)", price: 45, time: "24h - 48h" },
    { name: "El Hajeb", price: 45, time: "24h - 48h" },
    { name: "El jadida", price: 35, time: "24h - 48h" },
    { name: "El Kebab", price: 45, time: "48h - 96h" },
    { name: "El Kelaa Des Sraghna", price: 39, time: "24h - 72h" },
    { name: "El Ksiba", price: 45, time: "48h - 96h" },
    { name: "El Mansouria", price: 35, time: "48h - 96h" },
    { name: "El-afak", price: 39, time: "24h - 48h" },
    { name: "Er-Rich", price: 45, time: "48h - 96h" },
    { name: "Errachidia", price: 45, time: "24h - 72h" },
    { name: "Errouha", price: 45, time: "48h - 96h" },
    { name: "Essaouira", price: 35, time: "24h - 72h" },
    { name: "Essemara", price: 45, time: "48h - 96h" },
    { name: "Farquhana", price: 45, time: "24h - 48h" },
    { name: "Fes", price: 35, time: "24h - 48h" },
    { name: "Fezouata", price: 45, time: "48h - 96h" },
    { name: "Figuig", price: 45, time: "24h - 72h" },
    { name: "Fnideq", price: 39, time: "24h - 72h" },
    { name: "Foum Oudi", price: 39, time: "48h - 96h" },
    { name: "Fquih Ben Salah", price: 45, time: "24h - 72h" },
    { name: "Galaz", price: 45, time: "24h - 48h" },
    { name: "Ghafsai", price: 45, time: "48h - 96h" },
    { name: "Ghazoua", price: 39, time: "48h - 96h" },
    { name: "Goulmima", price: 45, time: "48h - 96h" },
    { name: "Guelmim", price: 39, time: "24h - 72h" },
    { name: "Guercif", price: 39, time: "24h - 72h" },
    { name: "Gueznaia", price: 45, time: "48h - 96h" },
    { name: "Had Boumoussa", price: 39, time: "48h - 96h" },
    { name: "Had Draa", price: 45, time: "24h - 72h" },
    { name: "Had Kaddour", price: 45, time: "48h - 96h" },
    { name: "Had Soualem", price: 35, time: "24h - 48h" },
    { name: "Haj Kaddour", price: 45, time: "48h - 96h" },
    { name: "Hajria Ouled Daoud", price: 45, time: "48h - 96h" },
    { name: "Harbile", price: 39, time: "24h - 72h" },
    { name: "Harhoura", price: 39, time: "24h - 48h" },
    { name: "Hettan", price: 39, time: "24h - 72h" },
    { name: "Ifran", price: 45, time: "24h - 72h" },
    { name: "Ighoud", price: 45, time: "48h - 96h" },
    { name: "Ighrem Laâlam", price: 39, time: "48h - 96h" },
    { name: "Ighrem N'ougdal", price: 45, time: "24h - 72h" },
    { name: "Imi Ouaddar", price: 45, time: "24h - 72h" },
    { name: "Imintanout", price: 45, time: "24h - 72h" },
    { name: "Imouzzer du Kandar", price: 45, time: "48h - 96h" },
    { name: "Imzouren", price: 45, time: "24h - 72h" },
    { name: "Inzegane", price: 35, time: "24h - 48h" },
    { name: "Issaguen", price: 45, time: "48h - 96h" },
    { name: "Jaadar", price: 39, time: "24h - 72h" },
    { name: "Jamaat Shaim", price: 45, time: "24h - 48h" },
    { name: "Jebila", price: 45, time: "48h - 96h" },
    { name: "Jerada", price: 45, time: "48h - 96h" },
    { name: "Jorf El Melha", price: 45, time: "24h - 72h" },
    { name: "KAA ASRASS", price: 45, time: "24h - 72h" },
    { name: "Kariat Arekmane", price: 45, time: "48h - 96h" },
    { name: "Kariat Ba Mohamed", price: 45, time: "48h - 96h" },
    { name: "Kasba Tadla", price: 39, time: "24h - 72h" },
    { name: "Kassita", price: 45, time: "48h - 96h" },
    { name: "Kelaat M'Gouna", price: 45, time: "48h - 96h" },
    { name: "Kenitra", price: 35, time: "24h - 48h" },
    { name: "Khemis Des Zemamra", price: 39, time: "24h - 48h" },
    { name: "Khemis du Sahel", price: 45, time: "24h - 72h" },
    { name: "Khenichet", price: 45, time: "24h - 72h" },
    { name: "Khenifra", price: 39, time: "24h - 72h" },
    { name: "Khlalfa", price: 45, time: "48h - 96h" },
    { name: "Khouribga", price: 35, time: "24h - 48h" },
    { name: "Ksar El Kebir", price: 39, time: "24h - 72h" },
    { name: "Ksar Sghir", price: 45, time: "48h - 96h" },
    { name: "Laaouamera", price: 45, time: "48h - 96h" },
    { name: "Laarache", price: 39, time: "24h - 48h" },
    { name: "Laattaouia", price: 39, time: "24h - 72h" },
    { name: "Laayayta", price: 39, time: "48h - 96h" },
    { name: "Lagfifat", price: 45, time: "48h - 96h" },
    { name: "Lahbichat", price: 45, time: "24h - 72h" },
    { name: "Lalla Mimouna", price: 45, time: "48h - 96h" },
    { name: "Loudaya", price: 39, time: "48h - 96h" },
    { name: "Loulad", price: 45, time: "48h - 96h" },
    { name: "M'hainra", price: 45, time: "24h - 72h" },
    { name: "M'hamid El Ghizlane", price: 45, time: "48h - 96h" },
    { name: "Madagh", price: 39, time: "24h - 72h" },
    { name: "Mariouari", price: 45, time: "48h - 96h" },
    { name: "Marrakech", price: 35, time: "24h - 48h" },
    { name: "Martil", price: 39, time: "24h - 48h" },
    { name: "Massa", price: 45, time: "48h - 96h" },
    { name: "Mdiq", price: 39, time: "24h - 72h" },
    { name: "Mechra Bel Ksiri", price: 45, time: "24h - 72h" },
    { name: "Mediouna", price: 35, time: "24h - 48h" },
    { name: "Mehdia", price: 39, time: "24h - 48h" },
    { name: "Mejat \"Région de Fès-Meknès\"", price: 45, time: "24h - 48h" },
    { name: "Mejjat - Région de Marrakech", price: 45, time: "48h - 96h" },
    { name: "Meknes", price: 35, time: "24h - 48h" },
    { name: "Melloussa", price: 45, time: "48h - 96h" },
    { name: "Merschouch", price: 45, time: "24h - 48h" },
    { name: "Mers El Kheir", price: 39, time: "24h - 48h" },
    { name: "Merzouga", price: 45, time: "48h - 96h" },
    { name: "Meskala", price: 45, time: "24h - 72h" },
    { name: "Messawerr Rasso", price: 45, time: "24h - 48h" },
    { name: "Mezoudia", price: 45, time: "24h - 72h" },
    { name: "Midar", price: 45, time: "48h - 96h" },
    { name: "Midelt", price: 45, time: "48h - 96h" },
    { name: "Mirleft", price: 45, time: "24h - 72h" },
    { name: "Missour", price: 45, time: "48h - 96h" },
    { name: "Mnar", price: 45, time: "48h - 96h" },
    { name: "Mohammedia", price: 35, time: "24h - 48h" },
    { name: "Mohammedia - Al Massira", price: 35, time: "24h - 48h" },
    { name: "Mohammedia - Al Wahda", price: 35, time: "24h - 48h" },
    { name: "Mohammedia - Alia", price: 35, time: "24h - 48h" },
    { name: "Mohammedia - Hassania", price: 35, time: "24h - 48h" },
    { name: "Mohammedia - Hay Wafa", price: 35, time: "24h - 48h" },
    { name: "Mohammedia - Kasbah", price: 35, time: "24h - 48h" },
    { name: "Mohammedia - Nassim", price: 35, time: "24h - 48h" },
    { name: "Mohammedia - Parc", price: 35, time: "24h - 48h" },
    { name: "N'Khila", price: 45, time: "48h - 96h" },
    { name: "N'Zala", price: 45, time: "48h - 96h" },
    { name: "Nador", price: 39, time: "24h - 48h" },
    { name: "Naïla", price: 45, time: "24h - 72h" },
    { name: "Nouaceur", price: 35, time: "24h - 48h" },
    { name: "Nouasseur", price: 35, time: "24h - 48h" },
    { name: "Nzal", price: 45, time: "48h - 96h" },
    { name: "Ouaouizeght", price: 39, time: "48h - 96h" },
    { name: "Oualidia", price: 39, time: "24h - 48h" },
    { name: "Ouarzazate", price: 39, time: "24h - 72h" },
    { name: "Oued Amlil", price: 39, time: "48h - 96h" },
    { name: "Oued laou", price: 45, time: "48h - 96h" },
    { name: "Oued Zem", price: 39, time: "24h - 48h" },
    { name: "Oujda", price: 35, time: "24h - 48h" },
    { name: "Oulad Abbou", price: 45, time: "24h - 48h" },
    { name: "Oulad Ali", price: 39, time: "48h - 96h" },
    { name: "Oulad Ayad", price: 39, time: "48h - 96h" },
    { name: "Oulad Azzouz Dar 16", price: 35, time: "24h - 48h" },
    { name: "Oulad Berhil", price: 45, time: "48h - 96h" },
    { name: "Oulad Dahhou", price: 45, time: "48h - 96h" },
    { name: "Oulad Frej", price: 45, time: "24h - 48h" },
    { name: "Oulad Hassoune", price: 45, time: "24h - 72h" },
    { name: "Oulad M'barek", price: 39, time: "48h - 96h" },
    { name: "Oulad Moumna", price: 45, time: "48h - 96h" },
    { name: "Oulad Said \"Région de Settat\"", price: 45, time: "24h - 48h" },
    { name: "Oulad Tayeb", price: 39, time: "48h - 96h" },
    { name: "Oulad Teima", price: 39, time: "24h - 72h" },
    { name: "Oulad Yaich", price: 39, time: "48h - 96h" },
    { name: "Oulad Youssef", price: 39, time: "48h - 96h" },
    { name: "Oulad Zmam", price: 39, time: "48h - 96h" },
    { name: "Oulmes", price: 45, time: "48h - 96h" },
    { name: "Oum El Aouda", price: 39, time: "24h - 48h" },
    { name: "Ounagha", price: 45, time: "24h - 72h" },
    { name: "Ourika", price: 45, time: "48h - 96h" },
    { name: "Paramount", price: 45, time: "24h - 48h" },
    { name: "Pas de Nom", price: 45, time: "24h - 72h" },
    { name: "Rabat", price: 35, time: "24h - 48h" },
    { name: "Safi", price: 39, time: "24h - 48h" },
    { name: "Salé", price: 35, time: "24h - 48h" },
    { name: "Sefrou", price: 39, time: "48h - 96h" },
    { name: "Settat", price: 39, time: "24h - 48h" },
    { name: "Sidi Bennour", price: 45, time: "48h - 96h" },
    { name: "Sidi Ifni", price: 45, time: "48h - 96h" },
    { name: "Sidi Kacem", price: 39, time: "24h - 48h" },
    { name: "Sidi Slimane", price: 39, time: "48h - 96h" },
    { name: "Sidi Yahia", price: 39, time: "48h - 96h" },
    { name: "Skhirat", price: 45, time: "24h - 48h" },
    { name: "Tafraout", price: 39, time: "48h - 96h" },
    { name: "Tahla", price: 39, time: "48h - 96h" },
    { name: "Tanger", price: 35, time: "24h - 48h" },
    { name: "Taounate", price: 39, time: "48h - 96h" },
    { name: "Taourirt", price: 39, time: "48h - 96h" },
    { name: "Tarfaya", price: 45, time: "48h - 96h" },
    { name: "Tata", price: 45, time: "48h - 96h" },
    { name: "Taza", price: 39, time: "24h - 48h" },
    { name: "Temara", price: 45, time: "24h - 48h" },
    { name: "Témara Other", price: 45, time: "24h - 48h" },
    { name: "Tétouan", price: 35, time: "24h - 48h" },
    { name: "Tiznit", price: 45, time: "48h - 96h" },
    { name: "Zagora", price: 45, time: "48h - 96h" },
    { name: "Zaio", price: 39, time: "48h - 96h" },
    { name: "Zemamra", price: 39, time: "48h - 96h" },
    { name: "Zoumi", price: 45, time: "24h - 48h" }
];
